---
title: Dettaglio
---


## EMILIA_ROMAGNA : 10


|station_eu_code |p16_19 |p20   |Valida | region_id|regione        |provincia          |
|:---------------|:------|:-----|:------|---------:|:--------------|:------------------|
|IT0187A         |TRUE   |FALSE |FALSE  |         8|EMILIA_ROMAGNA |Ferrara            |
|IT0721A         |TRUE   |FALSE |FALSE  |         8|EMILIA_ROMAGNA |Modena             |
|IT0755A         |TRUE   |FALSE |FALSE  |         8|EMILIA_ROMAGNA |Forli'-Cesena      |
|IT0895A         |TRUE   |FALSE |FALSE  |         8|EMILIA_ROMAGNA |Ravenna            |
|IT1029A         |TRUE   |FALSE |FALSE  |         8|EMILIA_ROMAGNA |Bologna            |
|IT1105A         |TRUE   |FALSE |FALSE  |         8|EMILIA_ROMAGNA |Parma              |
|IT1159A         |FALSE  |FALSE |FALSE  |         8|EMILIA_ROMAGNA |Bologna            |
|IT1920A         |TRUE   |FALSE |FALSE  |         8|EMILIA_ROMAGNA |Modena             |
|IT1923A         |TRUE   |FALSE |FALSE  |         8|EMILIA_ROMAGNA |Piacenza           |
|IT2156A         |TRUE   |FALSE |FALSE  |         8|EMILIA_ROMAGNA |Reggio nell'Emilia |


## PIEMONTE : 8


|station_eu_code |p16_19 |p20   |Valida | region_id|regione  |provincia   |
|:---------------|:------|:-----|:------|---------:|:--------|:-----------|
|IT0469A         |TRUE   |FALSE |FALSE  |         1|PIEMONTE |Torino      |
|IT0470A         |FALSE  |TRUE  |FALSE  |         1|PIEMONTE |Torino      |
|IT1128A         |TRUE   |FALSE |FALSE  |         1|PIEMONTE |Torino      |
|IT1130A         |FALSE  |TRUE  |FALSE  |         1|PIEMONTE |Torino      |
|IT1246A         |FALSE  |FALSE |FALSE  |         1|PIEMONTE |Biella      |
|IT1247A         |TRUE   |FALSE |FALSE  |         1|PIEMONTE |Biella      |
|IT1582A         |FALSE  |FALSE |FALSE  |         1|PIEMONTE |Alessandria |
|IT1903A         |FALSE  |TRUE  |FALSE  |         1|PIEMONTE |Asti        |


## LOMBARDIA : 17


|station_eu_code |p16_19 |p20   |Valida | region_id|regione   |provincia |
|:---------------|:------|:-----|:------|---------:|:---------|:---------|
|IT0477A         |FALSE  |TRUE  |FALSE  |         3|LOMBARDIA |Milano    |
|IT0692A         |FALSE  |TRUE  |FALSE  |         3|LOMBARDIA |Pavia     |
|IT0709A         |TRUE   |FALSE |FALSE  |         3|LOMBARDIA |Mantova   |
|IT0776A         |TRUE   |FALSE |FALSE  |         3|LOMBARDIA |Lecco     |
|IT0912A         |FALSE  |FALSE |FALSE  |         3|LOMBARDIA |Pavia     |
|IT0997A         |TRUE   |FALSE |FALSE  |         3|LOMBARDIA |Bergamo   |
|IT1016A         |FALSE  |FALSE |FALSE  |         3|LOMBARDIA |Milano    |
|IT1153A         |TRUE   |FALSE |FALSE  |         3|LOMBARDIA |Cremona   |
|IT1251A         |FALSE  |TRUE  |FALSE  |         3|LOMBARDIA |Brescia   |
|IT1286A         |FALSE  |FALSE |FALSE  |         3|LOMBARDIA |Lodi      |
|IT1385A         |FALSE  |TRUE  |FALSE  |         3|LOMBARDIA |Brescia   |
|IT1735A         |FALSE  |FALSE |FALSE  |         3|LOMBARDIA |Pavia     |
|IT1736A         |TRUE   |FALSE |FALSE  |         3|LOMBARDIA |Pavia     |
|IT1792A         |FALSE  |TRUE  |FALSE  |         3|LOMBARDIA |Milano    |
|IT1865A         |TRUE   |FALSE |FALSE  |         3|LOMBARDIA |Mantova   |
|IT1868A         |TRUE   |FALSE |FALSE  |         3|LOMBARDIA |Mantova   |
|IT2062A         |TRUE   |FALSE |FALSE  |         3|LOMBARDIA |Bergamo   |


## SICILIA : 10


|station_eu_code |p16_19 |p20   |Valida | region_id|regione |provincia     |
|:---------------|:------|:-----|:------|---------:|:-------|:-------------|
|IT0614A         |FALSE  |TRUE  |FALSE  |        19|SICILIA |Siracusa      |
|IT0813A         |FALSE  |TRUE  |FALSE  |        19|SICILIA |Caltanissetta |
|IT0815A         |FALSE  |TRUE  |FALSE  |        19|SICILIA |Caltanissetta |
|IT0817A         |FALSE  |TRUE  |FALSE  |        19|SICILIA |Caltanissetta |
|IT1079A         |FALSE  |FALSE |FALSE  |        19|SICILIA |Palermo       |
|IT1794A         |FALSE  |FALSE |FALSE  |        19|SICILIA |Messina       |
|IT1889A         |TRUE   |FALSE |FALSE  |        19|SICILIA |Palermo       |
|IT1898A         |FALSE  |TRUE  |FALSE  |        19|SICILIA |Trapani       |
|IT1997A         |FALSE  |TRUE  |FALSE  |        19|SICILIA |Messina       |
|IT2274A         |FALSE  |TRUE  |FALSE  |        19|SICILIA |Agrigento     |


## CAMPANIA : 18


|station_eu_code |p16_19 |p20   |Valida | region_id|regione  |provincia |
|:---------------|:------|:-----|:------|---------:|:--------|:---------|
|IT0898A         |FALSE  |TRUE  |FALSE  |        15|CAMPANIA |Napoli    |
|IT1487A         |FALSE  |TRUE  |FALSE  |        15|CAMPANIA |Caserta   |
|IT1491A         |FALSE  |TRUE  |FALSE  |        15|CAMPANIA |Napoli    |
|IT1493A         |FALSE  |TRUE  |FALSE  |        15|CAMPANIA |Napoli    |
|IT1497A         |FALSE  |TRUE  |FALSE  |        15|CAMPANIA |Napoli    |
|IT2210A         |FALSE  |TRUE  |FALSE  |        15|CAMPANIA |Avellino  |
|IT2211A         |FALSE  |FALSE |FALSE  |        15|CAMPANIA |Napoli    |
|IT2212A         |FALSE  |TRUE  |FALSE  |        15|CAMPANIA |Napoli    |
|IT2214A         |FALSE  |TRUE  |FALSE  |        15|CAMPANIA |Salerno   |
|IT2218A         |FALSE  |TRUE  |FALSE  |        15|CAMPANIA |Caserta   |
|IT2219A         |FALSE  |TRUE  |FALSE  |        15|CAMPANIA |Napoli    |
|IT2226A         |FALSE  |TRUE  |FALSE  |        15|CAMPANIA |Napoli    |
|IT2227A         |FALSE  |TRUE  |FALSE  |        15|CAMPANIA |Avellino  |
|IT2228A         |FALSE  |TRUE  |FALSE  |        15|CAMPANIA |Benevento |
|IT2268A         |FALSE  |TRUE  |FALSE  |        15|CAMPANIA |Salerno   |
|IT2269A         |FALSE  |TRUE  |FALSE  |        15|CAMPANIA |Salerno   |
|IT2270A         |FALSE  |TRUE  |FALSE  |        15|CAMPANIA |Napoli    |
|IT2271A         |FALSE  |TRUE  |FALSE  |        15|CAMPANIA |Caserta   |


## UMBRIA : 5


|station_eu_code |p16_19 |p20  |Valida | region_id|regione |provincia |
|:---------------|:------|:----|:------|---------:|:-------|:---------|
|IT1011A         |FALSE  |TRUE |FALSE  |        10|UMBRIA  |Terni     |
|IT1180A         |FALSE  |TRUE |FALSE  |        10|UMBRIA  |Perugia   |
|IT1728A         |FALSE  |TRUE |FALSE  |        10|UMBRIA  |Terni     |
|IT1860A         |FALSE  |TRUE |FALSE  |        10|UMBRIA  |Perugia   |
|IT2134A         |FALSE  |TRUE |FALSE  |        10|UMBRIA  |Terni     |


## PUGLIA : 4


|station_eu_code |p16_19 |p20  |Valida | region_id|regione |provincia |
|:---------------|:------|:----|:------|---------:|:-------|:---------|
|IT1658A         |FALSE  |TRUE |FALSE  |        16|PUGLIA  |Brindisi  |
|IT1704A         |FALSE  |TRUE |FALSE  |        16|PUGLIA  |Brindisi  |
|IT2139A         |FALSE  |TRUE |FALSE  |        16|PUGLIA  |Brindisi  |
|IT2148A         |FALSE  |TRUE |FALSE  |        16|PUGLIA  |Brindisi  |


## MOLISE : 2


|station_eu_code |p16_19 |p20   |Valida | region_id|regione |provincia  |
|:---------------|:------|:-----|:------|---------:|:-------|:----------|
|IT1801A         |FALSE  |FALSE |FALSE  |        14|MOLISE  |Campobasso |
|IT1962A         |TRUE   |FALSE |FALSE  |        14|MOLISE  |Isernia    |


## SARDEGNA : 1


|station_eu_code |p16_19 |p20  |Valida | region_id|regione  |provincia |
|:---------------|:------|:----|:------|---------:|:--------|:---------|
|IT1947A         |FALSE  |TRUE |FALSE  |        20|SARDEGNA |Cagliari  |


## FRIULI_VENEZIA_GIULIA : 1


|station_eu_code |p16_19 |p20  |Valida | region_id|regione               |provincia |
|:---------------|:------|:----|:------|---------:|:---------------------|:---------|
|IT2140A         |FALSE  |TRUE |FALSE  |         6|FRIULI_VENEZIA_GIULIA |Udine     |


## TOSCANA : 1


|station_eu_code |p16_19 |p20  |Valida | region_id|regione |provincia |
|:---------------|:------|:----|:------|---------:|:-------|:---------|
|IT2183A         |FALSE  |TRUE |FALSE  |         9|TOSCANA |Livorno   |


## BASILICATA : 1


|station_eu_code |p16_19 |p20  |Valida | region_id|regione    |provincia |
|:---------------|:------|:----|:------|---------:|:----------|:---------|
|IT2205A         |FALSE  |TRUE |FALSE  |        17|BASILICATA |Potenza   |

