---
author: 'GAM squad'
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
params:
  rdatafile: "~/R/pulvirus/analisi/GAM/output/no2_2.RData"
  titolo: "TEST"
---

---
title: `r params$titolo`
---


```{r, echo=FALSE, message=FALSE}
library(dplyr)
library(purrr)
library(magrittr)
library(mgcv)
library(logr)
library(knitr)
library(kableExtra)
library(stringr)
library(glue)
library(DT)
library(ggplot2)
library(datiInquinanti)
# basedir <- "~/R/pulvirus"

# estrazione parametri GAM check ####
estrai <- function(Out) {
  gam_obj <- mgcv:::anova.gam(Out) 
  return(gam_obj)
}
load(params$rdatafile)

basedir <- "~/R/pulvirus"

```

# Modello

```{r, echo=FALSE, results='asis'}
cat(names(models))
```

# AICS 

```{r, echo=FALSE}
aics <- models %>% 
  map(~ map_dbl(.x, AIC)) %>%  
  do.call(cbind, .) %>% 
  as.data.frame() %>% 
  set_colnames(c('AIC')) %>% 
  round(2) 

ggplot(aics) + 
  geom_col(aes(x = rownames(aics), y = AIC), fill = 'dodgerblue')  +  
  theme(axis.text.x = element_text(angle = 90)) + xlab("")

datatable(aics)
```


# R squared 

```{r, echo=FALSE}
rsquared <- models[[1]] %>%
  map(summary.gam) %>%
  map_dbl(~.$r.sq) %>% 
  as.data.frame() %>% 
  set_colnames(c('R')) %>% 
  round(3) 

ggplot(rsquared) + 
  geom_col(aes(x = rownames(rsquared), y = R), fill = 'red')  +  
  theme(axis.text.x = element_text(angle = 90)) + xlab("")

datatable(rsquared)
```

# P-values

```{r, echo=FALSE, results='asis'}
j <- 1
for (i in 1:length( models[[1]] ) ) {
  cat("\n\n## ", names(models[[1]][j]), "\n\n")
  
  b <- models[[1]][[j]]
  t <- estrai(models[[1]][[j]])
  t$s.table %>% 
    kable(format = "pipe", digits = 3) %>% 
    print()
  
  cat("\n\n")
  type <- "deviance"  ## "pearson" & "response" are other valid choices
  resid <- residuals(b, type = type)
  linpred <- napredict(b$na.action, b$linear.predictors)
  observed.y <- napredict(b$na.action, b$y)
  
  # grafici
  qq.gam(b, rep = 0, level = 0.9, type = type, rl.col = 2, rep.col = "gray80")
  
  plot(linpred, resid, main = "Resids vs. linear pred.", xlab = "linear predictor", ylab = "residuals")
  
  plot(fitted(b), observed.y, xlab = "Fitted Values", ylab = "Response", main = "Response vs. Fitted Values")
  cat("\n\n\n")

  j <- j + 1
}
```

 