---
title: Dettaglio
---


## SICILIA : 8


|station_eu_code |p16_19 |p20   |Valida | region_id|regione |provincia     |
|:---------------|:------|:-----|:------|---------:|:-------|:-------------|
|IT0611A         |TRUE   |FALSE |FALSE  |        19|SICILIA |Siracusa      |
|IT0620A         |TRUE   |FALSE |FALSE  |        19|SICILIA |Siracusa      |
|IT1076A         |FALSE  |FALSE |FALSE  |        19|SICILIA |Palermo       |
|IT1888A         |FALSE  |TRUE  |FALSE  |        19|SICILIA |Palermo       |
|IT1898A         |FALSE  |TRUE  |FALSE  |        19|SICILIA |Trapani       |
|IT1997A         |FALSE  |FALSE |FALSE  |        19|SICILIA |Messina       |
|IT2206A         |FALSE  |TRUE  |FALSE  |        19|SICILIA |Caltanissetta |
|IT2207A         |FALSE  |FALSE |FALSE  |        19|SICILIA |Caltanissetta |


## LOMBARDIA : 6


|station_eu_code |p16_19 |p20   |Valida | region_id|regione   |provincia |
|:---------------|:------|:-----|:------|---------:|:---------|:---------|
|IT0689A         |FALSE  |TRUE  |FALSE  |         3|LOMBARDIA |Pavia     |
|IT1648A         |TRUE   |FALSE |FALSE  |         3|LOMBARDIA |Como      |
|IT1737A         |TRUE   |FALSE |FALSE  |         3|LOMBARDIA |Brescia   |
|IT2014A         |TRUE   |FALSE |FALSE  |         3|LOMBARDIA |Lecco     |
|IT2063A         |TRUE   |FALSE |FALSE  |         3|LOMBARDIA |Cremona   |
|IT2232A         |TRUE   |FALSE |FALSE  |         3|LOMBARDIA |Milano    |


## LAZIO : 5


|station_eu_code |p16_19 |p20   |Valida | region_id|regione |provincia |
|:---------------|:------|:-----|:------|---------:|:-------|:---------|
|IT0888A         |FALSE  |TRUE  |FALSE  |        12|LAZIO   |Roma      |
|IT0956A         |FALSE  |TRUE  |FALSE  |        12|LAZIO   |Roma      |
|IT0957A         |FALSE  |TRUE  |FALSE  |        12|LAZIO   |Roma      |
|IT2249A         |FALSE  |TRUE  |FALSE  |        12|LAZIO   |Roma      |
|IT2254A         |FALSE  |FALSE |FALSE  |        12|LAZIO   |Roma      |


## CAMPANIA : 15


|station_eu_code |p16_19 |p20   |Valida | region_id|regione  |provincia |
|:---------------|:------|:-----|:------|---------:|:--------|:---------|
|IT0936A         |FALSE  |TRUE  |FALSE  |        15|CAMPANIA |Avellino  |
|IT1041A         |FALSE  |TRUE  |FALSE  |        15|CAMPANIA |Salerno   |
|IT1486A         |FALSE  |FALSE |FALSE  |        15|CAMPANIA |Caserta   |
|IT1488A         |FALSE  |TRUE  |FALSE  |        15|CAMPANIA |Caserta   |
|IT1497A         |FALSE  |TRUE  |FALSE  |        15|CAMPANIA |Napoli    |
|IT2212A         |FALSE  |FALSE |FALSE  |        15|CAMPANIA |Napoli    |
|IT2213A         |FALSE  |TRUE  |FALSE  |        15|CAMPANIA |Salerno   |
|IT2215A         |FALSE  |FALSE |FALSE  |        15|CAMPANIA |Benevento |
|IT2216A         |FALSE  |TRUE  |FALSE  |        15|CAMPANIA |Napoli    |
|IT2217A         |FALSE  |TRUE  |FALSE  |        15|CAMPANIA |Napoli    |
|IT2218A         |FALSE  |TRUE  |FALSE  |        15|CAMPANIA |Caserta   |
|IT2228A         |FALSE  |TRUE  |FALSE  |        15|CAMPANIA |Benevento |
|IT2268A         |FALSE  |TRUE  |FALSE  |        15|CAMPANIA |Salerno   |
|IT2269A         |FALSE  |TRUE  |FALSE  |        15|CAMPANIA |Salerno   |
|IT2270A         |FALSE  |TRUE  |FALSE  |        15|CAMPANIA |Napoli    |


## TOSCANA : 4


|station_eu_code |p16_19 |p20   |Valida | region_id|regione |provincia |
|:---------------|:------|:-----|:------|---------:|:-------|:---------|
|IT0950A         |TRUE   |FALSE |FALSE  |         9|TOSCANA |Arezzo    |
|IT1149A         |FALSE  |TRUE  |FALSE  |         9|TOSCANA |Pisa      |
|IT1644A         |TRUE   |FALSE |FALSE  |         9|TOSCANA |Lucca     |
|IT1681A         |TRUE   |FALSE |FALSE  |         9|TOSCANA |Arezzo    |


## FRIULI_VENEZIA_GIULIA : 6


|station_eu_code |p16_19 |p20   |Valida | region_id|regione               |provincia |
|:---------------|:------|:-----|:------|---------:|:---------------------|:---------|
|IT1090A         |TRUE   |FALSE |FALSE  |         6|FRIULI_VENEZIA_GIULIA |Trieste   |
|IT1170A         |FALSE  |TRUE  |FALSE  |         6|FRIULI_VENEZIA_GIULIA |Udine     |
|IT2131A         |FALSE  |TRUE  |FALSE  |         6|FRIULI_VENEZIA_GIULIA |Gorizia   |
|IT2132A         |FALSE  |TRUE  |FALSE  |         6|FRIULI_VENEZIA_GIULIA |Gorizia   |
|IT2133A         |FALSE  |TRUE  |FALSE  |         6|FRIULI_VENEZIA_GIULIA |Udine     |
|IT2182A         |FALSE  |TRUE  |FALSE  |         6|FRIULI_VENEZIA_GIULIA |Udine     |


## PIEMONTE : 18


|station_eu_code |p16_19 |p20   |Valida | region_id|regione  |provincia            |
|:---------------|:------|:-----|:------|---------:|:--------|:--------------------|
|IT1114A         |TRUE   |FALSE |FALSE  |         1|PIEMONTE |Torino               |
|IT1120A         |TRUE   |FALSE |FALSE  |         1|PIEMONTE |Torino               |
|IT1121A         |TRUE   |FALSE |FALSE  |         1|PIEMONTE |Torino               |
|IT1125A         |FALSE  |FALSE |FALSE  |         1|PIEMONTE |Torino               |
|IT1128A         |FALSE  |FALSE |FALSE  |         1|PIEMONTE |Torino               |
|IT1246A         |FALSE  |FALSE |FALSE  |         1|PIEMONTE |Biella               |
|IT1247A         |TRUE   |FALSE |FALSE  |         1|PIEMONTE |Biella               |
|IT1510A         |TRUE   |FALSE |FALSE  |         1|PIEMONTE |Verbano-Cusio-Ossola |
|IT1519A         |TRUE   |FALSE |FALSE  |         1|PIEMONTE |Cuneo                |
|IT1523A         |TRUE   |FALSE |FALSE  |         1|PIEMONTE |Asti                 |
|IT1524A         |TRUE   |FALSE |FALSE  |         1|PIEMONTE |Cuneo                |
|IT1529A         |TRUE   |FALSE |FALSE  |         1|PIEMONTE |Cuneo                |
|IT1532A         |TRUE   |FALSE |FALSE  |         1|PIEMONTE |Vercelli             |
|IT1830A         |FALSE  |FALSE |FALSE  |         1|PIEMONTE |Alessandria          |
|IT1877A         |TRUE   |FALSE |FALSE  |         1|PIEMONTE |Torino               |
|IT1878A         |TRUE   |FALSE |FALSE  |         1|PIEMONTE |Vercelli             |
|IT1904A         |TRUE   |FALSE |FALSE  |         1|PIEMONTE |Alessandria          |
|IT1948A         |TRUE   |FALSE |FALSE  |         1|PIEMONTE |Asti                 |


## BASILICATA : 2


|station_eu_code |p16_19 |p20  |Valida | region_id|regione    |provincia |
|:---------------|:------|:----|:------|---------:|:----------|:---------|
|IT1586A         |FALSE  |TRUE |FALSE  |        17|BASILICATA |Potenza   |
|IT1741A         |FALSE  |TRUE |FALSE  |        17|BASILICATA |Matera    |


## VENETO : 2


|station_eu_code |p16_19 |p20   |Valida | region_id|regione |provincia |
|:---------------|:------|:-----|:------|---------:|:-------|:---------|
|IT1596A         |TRUE   |FALSE |FALSE  |         5|VENETO  |Treviso   |
|IT2071A         |TRUE   |FALSE |FALSE  |         5|VENETO  |Padova    |


## PUGLIA : 8


|station_eu_code |p16_19 |p20   |Valida | region_id|regione |provincia             |
|:---------------|:------|:-----|:------|---------:|:-------|:---------------------|
|IT1614A         |TRUE   |FALSE |FALSE  |        16|PUGLIA  |Taranto               |
|IT1665A         |FALSE  |FALSE |FALSE  |        16|PUGLIA  |Lecce                 |
|IT1818A         |FALSE  |TRUE  |FALSE  |        16|PUGLIA  |Bari                  |
|IT1823A         |FALSE  |FALSE |FALSE  |        16|PUGLIA  |Bari                  |
|IT1953A         |FALSE  |TRUE  |FALSE  |        16|PUGLIA  |Lecce                 |
|IT2003A         |FALSE  |FALSE |FALSE  |        16|PUGLIA  |Barletta-Andria-Trani |
|IT2058A         |FALSE  |TRUE  |FALSE  |        16|PUGLIA  |Bari                  |
|IT2149A         |FALSE  |TRUE  |FALSE  |        16|PUGLIA  |Brindisi              |


## EMILIA_ROMAGNA : 3


|station_eu_code |p16_19 |p20   |Valida | region_id|regione        |provincia          |
|:---------------|:------|:-----|:------|---------:|:--------------|:------------------|
|IT1672A         |TRUE   |FALSE |FALSE  |         8|EMILIA_ROMAGNA |Reggio nell'Emilia |
|IT1927A         |TRUE   |FALSE |FALSE  |         8|EMILIA_ROMAGNA |Ravenna            |
|IT2097A         |TRUE   |FALSE |FALSE  |         8|EMILIA_ROMAGNA |Bologna            |


## MOLISE : 5


|station_eu_code |p16_19 |p20   |Valida | region_id|regione |provincia  |
|:---------------|:------|:-----|:------|---------:|:-------|:----------|
|IT1799A         |FALSE  |FALSE |FALSE  |        14|MOLISE  |Campobasso |
|IT1801A         |TRUE   |FALSE |FALSE  |        14|MOLISE  |Campobasso |
|IT1806A         |TRUE   |FALSE |FALSE  |        14|MOLISE  |Campobasso |
|IT1863A         |FALSE  |FALSE |FALSE  |        14|MOLISE  |Isernia    |
|IT1962A         |FALSE  |FALSE |FALSE  |        14|MOLISE  |Isernia    |


## SARDEGNA : 1


|station_eu_code |p16_19 |p20   |Valida | region_id|regione  |provincia |
|:---------------|:------|:-----|:------|---------:|:--------|:---------|
|IT1947A         |FALSE  |FALSE |FALSE  |        20|SARDEGNA |Cagliari  |

