---
title: Dettaglio
---

## VENETO : 22


|station_eu_code |p16_19 |p20  |Valida | region_id|regione |provincia |
|:---------------|:------|:----|:------|---------:|:-------|:---------|
|IT0448A         |TRUE   |TRUE |TRUE   |         5|VENETO  |Venezia   |
|IT0663A         |TRUE   |TRUE |TRUE   |         5|VENETO  |Vicenza   |
|IT0963A         |TRUE   |TRUE |TRUE   |         5|VENETO  |Venezia   |
|IT1065A         |TRUE   |TRUE |TRUE   |         5|VENETO  |Vicenza   |
|IT1177A         |TRUE   |TRUE |TRUE   |         5|VENETO  |Vicenza   |
|IT1213A         |TRUE   |TRUE |TRUE   |         5|VENETO  |Rovigo    |
|IT1214A         |TRUE   |TRUE |TRUE   |         5|VENETO  |Rovigo    |
|IT1222A         |TRUE   |TRUE |TRUE   |         5|VENETO  |Venezia   |
|IT1328A         |TRUE   |TRUE |TRUE   |         5|VENETO  |Treviso   |
|IT1340A         |TRUE   |TRUE |TRUE   |         5|VENETO  |Verona    |
|IT1453A         |TRUE   |TRUE |TRUE   |         5|VENETO  |Padova    |
|IT1535A         |TRUE   |TRUE |TRUE   |         5|VENETO  |Verona    |
|IT1590A         |TRUE   |TRUE |TRUE   |         5|VENETO  |Treviso   |
|IT1594A         |TRUE   |TRUE |TRUE   |         5|VENETO  |Belluno   |
|IT1619A         |TRUE   |TRUE |TRUE   |         5|VENETO  |Belluno   |
|IT1790A         |TRUE   |TRUE |TRUE   |         5|VENETO  |Belluno   |
|IT1791A         |TRUE   |TRUE |TRUE   |         5|VENETO  |Vicenza   |
|IT1848A         |TRUE   |TRUE |TRUE   |         5|VENETO  |Verona    |
|IT1870A         |TRUE   |TRUE |TRUE   |         5|VENETO  |Padova    |
|IT1871A         |TRUE   |TRUE |TRUE   |         5|VENETO  |Padova    |
|IT2072A         |TRUE   |TRUE |TRUE   |         5|VENETO  |Rovigo    |
|IT2243A         |TRUE   |TRUE |TRUE   |         5|VENETO  |Verona    |


## PA_BOLZANO : 4


|station_eu_code |p16_19 |p20  |Valida | region_id|regione    |provincia |
|:---------------|:------|:----|:------|---------:|:----------|:---------|
|IT0505A         |TRUE   |TRUE |TRUE   |        41|PA_BOLZANO |Bolzano   |
|IT0508A         |TRUE   |TRUE |TRUE   |        41|PA_BOLZANO |Bolzano   |
|IT1696A         |TRUE   |TRUE |TRUE   |        41|PA_BOLZANO |Bolzano   |
|IT2096A         |TRUE   |TRUE |TRUE   |        41|PA_BOLZANO |Bolzano   |


## EMILIA_ROMAGNA : 31


|station_eu_code |p16_19 |p20  |Valida | region_id|regione        |provincia          |
|:---------------|:------|:----|:------|---------:|:--------------|:------------------|
|IT0544A         |TRUE   |TRUE |TRUE   |         8|EMILIA_ROMAGNA |Piacenza           |
|IT0804A         |TRUE   |TRUE |TRUE   |         8|EMILIA_ROMAGNA |Parma              |
|IT0892A         |TRUE   |TRUE |TRUE   |         8|EMILIA_ROMAGNA |Bologna            |
|IT0903A         |TRUE   |TRUE |TRUE   |         8|EMILIA_ROMAGNA |Reggio nell'Emilia |
|IT0940A         |TRUE   |TRUE |TRUE   |         8|EMILIA_ROMAGNA |Reggio nell'Emilia |
|IT1043A         |TRUE   |TRUE |TRUE   |         8|EMILIA_ROMAGNA |Rimini             |
|IT1048A         |TRUE   |TRUE |TRUE   |         8|EMILIA_ROMAGNA |Forli'-Cesena      |
|IT1152A         |TRUE   |TRUE |TRUE   |         8|EMILIA_ROMAGNA |Modena             |
|IT1179A         |TRUE   |TRUE |TRUE   |         8|EMILIA_ROMAGNA |Ferrara            |
|IT1204A         |TRUE   |TRUE |TRUE   |         8|EMILIA_ROMAGNA |Ravenna            |
|IT1451A         |TRUE   |TRUE |TRUE   |         8|EMILIA_ROMAGNA |Bologna            |
|IT1771A         |TRUE   |TRUE |TRUE   |         8|EMILIA_ROMAGNA |Modena             |
|IT1908A         |TRUE   |TRUE |TRUE   |         8|EMILIA_ROMAGNA |Forli'-Cesena      |
|IT1910A         |TRUE   |TRUE |TRUE   |         8|EMILIA_ROMAGNA |Parma              |
|IT1911A         |TRUE   |TRUE |TRUE   |         8|EMILIA_ROMAGNA |Parma              |
|IT1914A         |TRUE   |TRUE |TRUE   |         8|EMILIA_ROMAGNA |Reggio nell'Emilia |
|IT1915A         |TRUE   |TRUE |TRUE   |         8|EMILIA_ROMAGNA |Rimini             |
|IT1916A         |TRUE   |TRUE |TRUE   |         8|EMILIA_ROMAGNA |Rimini             |
|IT1917A         |TRUE   |TRUE |TRUE   |         8|EMILIA_ROMAGNA |Ferrara            |
|IT1918A         |TRUE   |TRUE |TRUE   |         8|EMILIA_ROMAGNA |Ferrara            |
|IT1919A         |TRUE   |TRUE |TRUE   |         8|EMILIA_ROMAGNA |Ferrara            |
|IT1921A         |TRUE   |TRUE |TRUE   |         8|EMILIA_ROMAGNA |Modena             |
|IT1924A         |TRUE   |TRUE |TRUE   |         8|EMILIA_ROMAGNA |Piacenza           |
|IT1928A         |TRUE   |TRUE |TRUE   |         8|EMILIA_ROMAGNA |Ravenna            |
|IT1975A         |TRUE   |TRUE |TRUE   |         8|EMILIA_ROMAGNA |Piacenza           |
|IT2027A         |TRUE   |TRUE |TRUE   |         8|EMILIA_ROMAGNA |Forli'-Cesena      |
|IT2073A         |TRUE   |TRUE |TRUE   |         8|EMILIA_ROMAGNA |Modena             |
|IT2074A         |TRUE   |TRUE |TRUE   |         8|EMILIA_ROMAGNA |Piacenza           |
|IT2075A         |TRUE   |TRUE |TRUE   |         8|EMILIA_ROMAGNA |Bologna            |
|IT2158A         |TRUE   |TRUE |TRUE   |         8|EMILIA_ROMAGNA |Rimini             |
|IT2209A         |TRUE   |TRUE |TRUE   |         8|EMILIA_ROMAGNA |Ravenna            |


## PA_TRENTO : 4


|station_eu_code |p16_19 |p20  |Valida | region_id|regione   |provincia |
|:---------------|:------|:----|:------|---------:|:---------|:---------|
|IT0703A         |TRUE   |TRUE |TRUE   |        42|PA_TRENTO |Trento    |
|IT0753A         |TRUE   |TRUE |TRUE   |        42|PA_TRENTO |Trento    |
|IT1037A         |TRUE   |TRUE |TRUE   |        42|PA_TRENTO |Trento    |
|IT1930A         |TRUE   |TRUE |TRUE   |        42|PA_TRENTO |Trento    |


## LOMBARDIA : 40


|station_eu_code |p16_19 |p20  |Valida | region_id|regione   |provincia             |
|:---------------|:------|:----|:------|---------:|:---------|:---------------------|
|IT0706A         |TRUE   |TRUE |TRUE   |         3|LOMBARDIA |Milano                |
|IT0707A         |TRUE   |TRUE |TRUE   |         3|LOMBARDIA |Bergamo               |
|IT0732A         |TRUE   |TRUE |TRUE   |         3|LOMBARDIA |Varese                |
|IT0740A         |TRUE   |TRUE |TRUE   |         3|LOMBARDIA |Brescia               |
|IT0741A         |TRUE   |TRUE |TRUE   |         3|LOMBARDIA |Brescia               |
|IT0743A         |TRUE   |TRUE |TRUE   |         3|LOMBARDIA |Brescia               |
|IT0775A         |TRUE   |TRUE |TRUE   |         3|LOMBARDIA |Lecco                 |
|IT0839A         |TRUE   |TRUE |TRUE   |         3|LOMBARDIA |Cremona               |
|IT0842A         |TRUE   |TRUE |TRUE   |         3|LOMBARDIA |Cremona               |
|IT0908A         |TRUE   |TRUE |TRUE   |         3|LOMBARDIA |Sondrio               |
|IT0912A         |TRUE   |TRUE |TRUE   |         3|LOMBARDIA |Pavia                 |
|IT1174A         |TRUE   |TRUE |TRUE   |         3|LOMBARDIA |Milano                |
|IT1190A         |TRUE   |TRUE |TRUE   |         3|LOMBARDIA |Sondrio               |
|IT1203A         |TRUE   |TRUE |TRUE   |         3|LOMBARDIA |Milano                |
|IT1288A         |TRUE   |TRUE |TRUE   |         3|LOMBARDIA |Lodi                  |
|IT1385A         |TRUE   |TRUE |TRUE   |         3|LOMBARDIA |Brescia               |
|IT1388A         |TRUE   |TRUE |TRUE   |         3|LOMBARDIA |Mantova               |
|IT1459A         |TRUE   |TRUE |TRUE   |         3|LOMBARDIA |Varese                |
|IT1463A         |TRUE   |TRUE |TRUE   |         3|LOMBARDIA |Bergamo               |
|IT1464A         |TRUE   |TRUE |TRUE   |         3|LOMBARDIA |Bergamo               |
|IT1650A         |TRUE   |TRUE |TRUE   |         3|LOMBARDIA |Varese                |
|IT1692A         |TRUE   |TRUE |TRUE   |         3|LOMBARDIA |Milano                |
|IT1734A         |TRUE   |TRUE |TRUE   |         3|LOMBARDIA |Lecco                 |
|IT1735A         |TRUE   |TRUE |TRUE   |         3|LOMBARDIA |Pavia                 |
|IT1736A         |TRUE   |TRUE |TRUE   |         3|LOMBARDIA |Pavia                 |
|IT1739A         |TRUE   |TRUE |TRUE   |         3|LOMBARDIA |Cremona               |
|IT1743A         |TRUE   |TRUE |TRUE   |         3|LOMBARDIA |Monza e della Brianza |
|IT1746A         |TRUE   |TRUE |TRUE   |         3|LOMBARDIA |Pavia                 |
|IT1812A         |TRUE   |TRUE |TRUE   |         3|LOMBARDIA |Lecco                 |
|IT1826A         |TRUE   |TRUE |TRUE   |         3|LOMBARDIA |Lecco                 |
|IT1865A         |TRUE   |TRUE |TRUE   |         3|LOMBARDIA |Mantova               |
|IT1868A         |TRUE   |TRUE |TRUE   |         3|LOMBARDIA |Mantova               |
|IT1873A         |TRUE   |TRUE |TRUE   |         3|LOMBARDIA |Varese                |
|IT1876A         |TRUE   |TRUE |TRUE   |         3|LOMBARDIA |Bergamo               |
|IT1964A         |TRUE   |TRUE |TRUE   |         3|LOMBARDIA |Lodi                  |
|IT1965A         |TRUE   |TRUE |TRUE   |         3|LOMBARDIA |Lodi                  |
|IT1967A         |TRUE   |TRUE |TRUE   |         3|LOMBARDIA |Sondrio               |
|IT2007A         |TRUE   |TRUE |TRUE   |         3|LOMBARDIA |Como                  |
|IT2098A         |TRUE   |TRUE |TRUE   |         3|LOMBARDIA |Monza e della Brianza |
|IT2230A         |TRUE   |TRUE |TRUE   |         3|LOMBARDIA |Mantova               |


## LAZIO : 18


|station_eu_code |p16_19 |p20  |Valida | region_id|regione |provincia |
|:---------------|:------|:----|:------|---------:|:-------|:---------|
|IT0863A         |TRUE   |TRUE |TRUE   |        12|LAZIO   |Viterbo   |
|IT0867A         |TRUE   |TRUE |TRUE   |        12|LAZIO   |Rieti     |
|IT0869A         |TRUE   |TRUE |TRUE   |        12|LAZIO   |Latina    |
|IT0884A         |TRUE   |TRUE |TRUE   |        12|LAZIO   |Roma      |
|IT0885A         |TRUE   |TRUE |TRUE   |        12|LAZIO   |Roma      |
|IT0952A         |TRUE   |TRUE |TRUE   |        12|LAZIO   |Roma      |
|IT0953A         |TRUE   |TRUE |TRUE   |        12|LAZIO   |Roma      |
|IT0992A         |TRUE   |TRUE |TRUE   |        12|LAZIO   |Frosinone |
|IT1176A         |TRUE   |TRUE |TRUE   |        12|LAZIO   |Roma      |
|IT1835A         |TRUE   |TRUE |TRUE   |        12|LAZIO   |Roma      |
|IT1836A         |TRUE   |TRUE |TRUE   |        12|LAZIO   |Roma      |
|IT1906A         |TRUE   |TRUE |TRUE   |        12|LAZIO   |Roma      |
|IT2012A         |TRUE   |TRUE |TRUE   |        12|LAZIO   |Roma      |
|IT2013A         |TRUE   |TRUE |TRUE   |        12|LAZIO   |Frosinone |
|IT2023A         |TRUE   |TRUE |TRUE   |        12|LAZIO   |Viterbo   |
|IT2172A         |TRUE   |TRUE |TRUE   |        12|LAZIO   |Roma      |
|IT2173A         |TRUE   |TRUE |TRUE   |        12|LAZIO   |Latina    |
|IT2265A         |TRUE   |TRUE |TRUE   |        12|LAZIO   |Roma      |


## TOSCANA : 6


|station_eu_code |p16_19 |p20  |Valida | region_id|regione |provincia |
|:---------------|:------|:----|:------|---------:|:-------|:---------|
|IT0883A         |TRUE   |TRUE |TRUE   |         9|TOSCANA |Firenze   |
|IT1071A         |TRUE   |TRUE |TRUE   |         9|TOSCANA |Pisa      |
|IT1110A         |TRUE   |TRUE |TRUE   |         9|TOSCANA |Pisa      |
|IT1553A         |TRUE   |TRUE |TRUE   |         9|TOSCANA |Pistoia   |
|IT1942A         |TRUE   |TRUE |TRUE   |         9|TOSCANA |Grosseto  |
|IT2153A         |TRUE   |TRUE |TRUE   |         9|TOSCANA |Firenze   |


## FRIULI_VENEZIA_GIULIA : 8


|station_eu_code |p16_19 |p20  |Valida | region_id|regione               |provincia |
|:---------------|:------|:----|:------|---------:|:---------------------|:---------|
|IT0966A         |TRUE   |TRUE |TRUE   |         6|FRIULI_VENEZIA_GIULIA |Udine     |
|IT1112A         |TRUE   |TRUE |TRUE   |         6|FRIULI_VENEZIA_GIULIA |Pordenone |
|IT1166A         |TRUE   |TRUE |TRUE   |         6|FRIULI_VENEZIA_GIULIA |Udine     |
|IT1168A         |TRUE   |TRUE |TRUE   |         6|FRIULI_VENEZIA_GIULIA |Udine     |
|IT2115A         |TRUE   |TRUE |TRUE   |         6|FRIULI_VENEZIA_GIULIA |Pordenone |
|IT2129A         |TRUE   |TRUE |TRUE   |         6|FRIULI_VENEZIA_GIULIA |Gorizia   |
|IT2130A         |TRUE   |TRUE |TRUE   |         6|FRIULI_VENEZIA_GIULIA |Gorizia   |
|IT2169A         |TRUE   |TRUE |TRUE   |         6|FRIULI_VENEZIA_GIULIA |Udine     |


## VALLE_AOSTA : 3


|station_eu_code |p16_19 |p20  |Valida | region_id|regione     |provincia |
|:---------------|:------|:----|:------|---------:|:-----------|:---------|
|IT0983A         |TRUE   |TRUE |TRUE   |         2|VALLE_AOSTA |Aosta     |
|IT0988A         |TRUE   |TRUE |TRUE   |         2|VALLE_AOSTA |Aosta     |
|IT2233A         |TRUE   |TRUE |TRUE   |         2|VALLE_AOSTA |Aosta     |


## PA_TRENTO : 1


|station_eu_code |p16_19 |p20  |Valida | region_id|regione   |provincia |
|:---------------|:------|:----|:------|---------:|:---------|:---------|
|IT1191A         |TRUE   |TRUE |TRUE   |         4|PA_TRENTO |Trento    |


## BASILICATA : 5


|station_eu_code |p16_19 |p20  |Valida | region_id|regione    |provincia |
|:---------------|:------|:----|:------|---------:|:----------|:---------|
|IT1193A         |TRUE   |TRUE |TRUE   |        17|BASILICATA |Potenza   |
|IT1742A         |TRUE   |TRUE |TRUE   |        17|BASILICATA |Potenza   |
|IT1895A         |TRUE   |TRUE |TRUE   |        17|BASILICATA |Matera    |
|IT1897A         |TRUE   |TRUE |TRUE   |        17|BASILICATA |Potenza   |
|IT2205A         |TRUE   |TRUE |TRUE   |        17|BASILICATA |Potenza   |


## SARDEGNA : 16


|station_eu_code |p16_19 |p20  |Valida | region_id|regione  |provincia         |
|:---------------|:------|:----|:------|---------:|:--------|:-----------------|
|IT1243A         |TRUE   |TRUE |TRUE   |        20|SARDEGNA |Sassari           |
|IT1269A         |TRUE   |TRUE |TRUE   |        20|SARDEGNA |Cagliari          |
|IT1375A         |TRUE   |TRUE |TRUE   |        20|SARDEGNA |Cagliari          |
|IT1397A         |TRUE   |TRUE |TRUE   |        20|SARDEGNA |Cagliari          |
|IT1407A         |TRUE   |TRUE |TRUE   |        20|SARDEGNA |Nuoro             |
|IT1576A         |TRUE   |TRUE |TRUE   |        20|SARDEGNA |Carbonia-Iglesias |
|IT1993A         |TRUE   |TRUE |TRUE   |        20|SARDEGNA |Cagliari          |
|IT1996A         |TRUE   |TRUE |TRUE   |        20|SARDEGNA |Nuoro             |
|IT2005A         |TRUE   |TRUE |TRUE   |        20|SARDEGNA |Olbia-Tempio      |
|IT2009A         |TRUE   |TRUE |TRUE   |        20|SARDEGNA |Sassari           |
|IT2010A         |TRUE   |TRUE |TRUE   |        20|SARDEGNA |Sassari           |
|IT2011A         |TRUE   |TRUE |TRUE   |        20|SARDEGNA |Cagliari          |
|IT2040A         |TRUE   |TRUE |TRUE   |        20|SARDEGNA |Cagliari          |
|IT2049A         |TRUE   |TRUE |TRUE   |        20|SARDEGNA |Cagliari          |
|IT2056A         |TRUE   |TRUE |TRUE   |        20|SARDEGNA |Cagliari          |
|IT2059A         |TRUE   |TRUE |TRUE   |        20|SARDEGNA |Sassari           |


## PUGLIA : 6


|station_eu_code |p16_19 |p20  |Valida | region_id|regione |provincia |
|:---------------|:------|:----|:------|---------:|:-------|:---------|
|IT1601A         |TRUE   |TRUE |TRUE   |        16|PUGLIA  |Foggia    |
|IT1624A         |TRUE   |TRUE |TRUE   |        16|PUGLIA  |Bari      |
|IT1679A         |TRUE   |TRUE |TRUE   |        16|PUGLIA  |Taranto   |
|IT2139A         |TRUE   |TRUE |TRUE   |        16|PUGLIA  |Brindisi  |
|IT2142A         |TRUE   |TRUE |TRUE   |        16|PUGLIA  |Foggia    |
|IT2144A         |TRUE   |TRUE |TRUE   |        16|PUGLIA  |Bari      |


## PIEMONTE : 1


|station_eu_code |p16_19 |p20  |Valida | region_id|regione  |provincia |
|:---------------|:------|:----|:------|---------:|:--------|:---------|
|IT1788A         |TRUE   |TRUE |TRUE   |         1|PIEMONTE |Torino    |


## MOLISE : 1


|station_eu_code |p16_19 |p20  |Valida | region_id|regione |provincia  |
|:---------------|:------|:----|:------|---------:|:-------|:----------|
|IT1798A         |TRUE   |TRUE |TRUE   |        14|MOLISE  |Campobasso |


## SICILIA : 3


|station_eu_code |p16_19 |p20  |Valida | region_id|regione |provincia |
|:---------------|:------|:----|:------|---------:|:-------|:---------|
|IT1889A         |TRUE   |TRUE |TRUE   |        19|SICILIA |Palermo   |
|IT1890A         |TRUE   |TRUE |TRUE   |        19|SICILIA |Enna      |
|IT1899A         |TRUE   |TRUE |TRUE   |        19|SICILIA |Catania   |

