## Regioni

[TOSCANA](TOSCANA/TOSCANA_riepilogo.html)

[EMILIA_ROMAGNA](EMILIA_ROMAGNA/EMILIA_ROMAGNA_riepilogo.html)

[LOMBARDIA](LOMBARDIA/LOMBARDIA_riepilogo.html)

[VENETO](VENETO/VENETO_riepilogo.html)

[PIEMONTE](PIEMONTE/PIEMONTE_riepilogo.html)

[PA_BOLZANO](PA_BOLZANO/PA_BOLZANO_riepilogo.html)

[PA_TRENTO](PA_TRENTO/PA_TRENTO_riepilogo.html)

[SICILIA](SICILIA/SICILIA_riepilogo.html)

[LAZIO](LAZIO/LAZIO_riepilogo.html)

[CAMPANIA](CAMPANIA/CAMPANIA_riepilogo.html)

[FRIULI_VENEZIA_GIULIA](FRIULI_VENEZIA_GIULIA/FRIULI_VENEZIA_GIULIA_riepilogo.html)

[VALLE_AOSTA](VALLE_AOSTA/VALLE_AOSTA_riepilogo.html)

[UMBRIA](UMBRIA/UMBRIA_riepilogo.html)

[BASILICATA](BASILICATA/BASILICATA_riepilogo.html)

[SARDEGNA](SARDEGNA/SARDEGNA_riepilogo.html)

[PUGLIA](PUGLIA/PUGLIA_riepilogo.html)

[MOLISE](MOLISE/MOLISE_riepilogo.html)

