

|station_eu_code |p16_19 |p20   |valida | pollutant_fk| region_id|regione |provincia     |
|:---------------|:------|:-----|:------|------------:|---------:|:-------|:-------------|
|IT0611A         |FALSE  |TRUE  |FALSE  |            5|        19|SICILIA |Siracusa      |
|IT0611A         |TRUE   |TRUE  |TRUE   |            8|        19|SICILIA |Siracusa      |
|IT0614A         |TRUE   |TRUE  |TRUE   |            8|        19|SICILIA |Siracusa      |
|IT0614A         |TRUE   |TRUE  |TRUE   |            5|        19|SICILIA |Siracusa      |
|IT0614A         |FALSE  |TRUE  |FALSE  |           20|        19|SICILIA |Siracusa      |
|IT0614A         |FALSE  |TRUE  |FALSE  |         6001|        19|SICILIA |Siracusa      |
|IT0618A         |TRUE   |FALSE |FALSE  |            5|        19|SICILIA |Siracusa      |
|IT0618A         |TRUE   |TRUE  |TRUE   |            8|        19|SICILIA |Siracusa      |
|IT0620A         |FALSE  |TRUE  |FALSE  |            5|        19|SICILIA |Siracusa      |
|IT0620A         |TRUE   |TRUE  |TRUE   |            8|        19|SICILIA |Siracusa      |
|IT0813A         |FALSE  |TRUE  |FALSE  |           20|        19|SICILIA |Caltanissetta |
|IT0813A         |FALSE  |TRUE  |FALSE  |            8|        19|SICILIA |Caltanissetta |
|IT0813A         |FALSE  |TRUE  |FALSE  |           10|        19|SICILIA |Caltanissetta |
|IT0815A         |FALSE  |TRUE  |FALSE  |            8|        19|SICILIA |Caltanissetta |
|IT0815A         |FALSE  |TRUE  |FALSE  |            5|        19|SICILIA |Caltanissetta |
|IT0815A         |FALSE  |TRUE  |FALSE  |           20|        19|SICILIA |Caltanissetta |
|IT0817A         |FALSE  |TRUE  |FALSE  |           20|        19|SICILIA |Caltanissetta |
|IT0817A         |FALSE  |TRUE  |FALSE  |            8|        19|SICILIA |Caltanissetta |
|IT1076A         |FALSE  |FALSE |FALSE  |            5|        19|SICILIA |Palermo       |
|IT1076A         |FALSE  |FALSE |FALSE  |            8|        19|SICILIA |Palermo       |
|IT1078A         |FALSE  |FALSE |FALSE  |            5|        19|SICILIA |Palermo       |
|IT1079A         |FALSE  |FALSE |FALSE  |           20|        19|SICILIA |Palermo       |
|IT1079A         |FALSE  |FALSE |FALSE  |            8|        19|SICILIA |Palermo       |
|IT1079A         |FALSE  |FALSE |FALSE  |            5|        19|SICILIA |Palermo       |
|IT1346A         |TRUE   |TRUE  |TRUE   |            8|        19|SICILIA |Siracusa      |
|IT1346A         |TRUE   |TRUE  |TRUE   |           20|        19|SICILIA |Siracusa      |
|IT1346A         |TRUE   |TRUE  |TRUE   |            5|        19|SICILIA |Siracusa      |
|IT1440A         |TRUE   |FALSE |FALSE  |            5|        19|SICILIA |Siracusa      |
|IT1440A         |TRUE   |FALSE |FALSE  |            8|        19|SICILIA |Siracusa      |
|IT1552A         |TRUE   |FALSE |FALSE  |            8|        19|SICILIA |Palermo       |
|IT1552A         |FALSE  |FALSE |FALSE  |            5|        19|SICILIA |Palermo       |
|IT1552A         |FALSE  |FALSE |FALSE  |           10|        19|SICILIA |Palermo       |
|IT1794A         |FALSE  |FALSE |FALSE  |           20|        19|SICILIA |Messina       |
|IT1794A         |FALSE  |FALSE |FALSE  |            8|        19|SICILIA |Messina       |
|IT1888A         |TRUE   |TRUE  |TRUE   |           20|        19|SICILIA |Palermo       |
|IT1888A         |TRUE   |TRUE  |TRUE   |            5|        19|SICILIA |Palermo       |
|IT1888A         |TRUE   |TRUE  |TRUE   |            8|        19|SICILIA |Palermo       |
|IT1888A         |TRUE   |TRUE  |TRUE   |           10|        19|SICILIA |Palermo       |
|IT1889A         |TRUE   |TRUE  |TRUE   |            8|        19|SICILIA |Palermo       |
|IT1889A         |TRUE   |TRUE  |TRUE   |           10|        19|SICILIA |Palermo       |
|IT1889A         |TRUE   |TRUE  |TRUE   |            5|        19|SICILIA |Palermo       |
|IT1889A         |TRUE   |FALSE |FALSE  |           20|        19|SICILIA |Palermo       |
|IT1890A         |TRUE   |TRUE  |TRUE   |           10|        19|SICILIA |Enna          |
|IT1890A         |TRUE   |TRUE  |TRUE   |            8|        19|SICILIA |Enna          |
|IT1890A         |TRUE   |TRUE  |TRUE   |            5|        19|SICILIA |Enna          |
|IT1890A         |TRUE   |TRUE  |TRUE   |           20|        19|SICILIA |Enna          |
|IT1898A         |FALSE  |TRUE  |FALSE  |           20|        19|SICILIA |Trapani       |
|IT1898A         |FALSE  |TRUE  |FALSE  |           10|        19|SICILIA |Trapani       |
|IT1898A         |TRUE   |TRUE  |TRUE   |            5|        19|SICILIA |Trapani       |
|IT1898A         |FALSE  |TRUE  |FALSE  |            8|        19|SICILIA |Trapani       |
|IT1899A         |TRUE   |FALSE |FALSE  |            5|        19|SICILIA |Catania       |
|IT1899A         |TRUE   |TRUE  |TRUE   |            8|        19|SICILIA |Catania       |
|IT1997A         |FALSE  |TRUE  |FALSE  |           20|        19|SICILIA |Messina       |
|IT1997A         |FALSE  |TRUE  |FALSE  |           10|        19|SICILIA |Messina       |
|IT1997A         |FALSE  |FALSE |FALSE  |            8|        19|SICILIA |Messina       |
|IT2206A         |FALSE  |TRUE  |FALSE  |            8|        19|SICILIA |Caltanissetta |
|IT2206A         |FALSE  |TRUE  |FALSE  |            5|        19|SICILIA |Caltanissetta |
|IT2207A         |FALSE  |TRUE  |FALSE  |            8|        19|SICILIA |Caltanissetta |
|IT2274A         |FALSE  |TRUE  |FALSE  |            5|        19|SICILIA |Agrigento     |
|IT2274A         |FALSE  |TRUE  |FALSE  |           10|        19|SICILIA |Agrigento     |
|IT2274A         |FALSE  |TRUE  |FALSE  |         6001|        19|SICILIA |Agrigento     |
|IT2274A         |FALSE  |TRUE  |FALSE  |            8|        19|SICILIA |Agrigento     |
|IT2274A         |FALSE  |TRUE  |FALSE  |           20|        19|SICILIA |Agrigento     |
