---
title: Dettaglio
---

## LOMBARDIA : 18


|station_eu_code |p16_19 |p20  |Valida | region_id|regione   |provincia |
|:---------------|:------|:----|:------|---------:|:---------|:---------|
|IT0477A         |TRUE   |TRUE |TRUE   |         3|LOMBARDIA |Milano    |
|IT0707A         |TRUE   |TRUE |TRUE   |         3|LOMBARDIA |Bergamo   |
|IT0740A         |TRUE   |TRUE |TRUE   |         3|LOMBARDIA |Brescia   |
|IT0761A         |TRUE   |TRUE |TRUE   |         3|LOMBARDIA |Milano    |
|IT0776A         |TRUE   |TRUE |TRUE   |         3|LOMBARDIA |Lecco     |
|IT0778A         |TRUE   |TRUE |TRUE   |         3|LOMBARDIA |Bergamo   |
|IT0846A         |TRUE   |TRUE |TRUE   |         3|LOMBARDIA |Brescia   |
|IT0906A         |TRUE   |TRUE |TRUE   |         3|LOMBARDIA |Sondrio   |
|IT0997A         |TRUE   |TRUE |TRUE   |         3|LOMBARDIA |Bergamo   |
|IT1104A         |TRUE   |TRUE |TRUE   |         3|LOMBARDIA |Pavia     |
|IT1190A         |TRUE   |TRUE |TRUE   |         3|LOMBARDIA |Sondrio   |
|IT1251A         |TRUE   |TRUE |TRUE   |         3|LOMBARDIA |Brescia   |
|IT1286A         |TRUE   |TRUE |TRUE   |         3|LOMBARDIA |Lodi      |
|IT1459A         |TRUE   |TRUE |TRUE   |         3|LOMBARDIA |Varese    |
|IT1588A         |TRUE   |TRUE |TRUE   |         3|LOMBARDIA |Varese    |
|IT1735A         |TRUE   |TRUE |TRUE   |         3|LOMBARDIA |Pavia     |
|IT1792A         |TRUE   |TRUE |TRUE   |         3|LOMBARDIA |Milano    |
|IT1869A         |TRUE   |TRUE |TRUE   |         3|LOMBARDIA |Mantova   |


## TOSCANA : 2


|station_eu_code |p16_19 |p20  |Valida | region_id|regione |provincia |
|:---------------|:------|:----|:------|---------:|:-------|:---------|
|IT0832A         |TRUE   |TRUE |TRUE   |         9|TOSCANA |Arezzo    |
|IT1560A         |TRUE   |TRUE |TRUE   |         9|TOSCANA |Livorno   |


## LAZIO : 2


|station_eu_code |p16_19 |p20  |Valida | region_id|regione |provincia |
|:---------------|:------|:----|:------|---------:|:-------|:---------|
|IT0863A         |TRUE   |TRUE |TRUE   |        12|LAZIO   |Viterbo   |
|IT1200A         |TRUE   |TRUE |TRUE   |        12|LAZIO   |Frosinone |


## VENETO : 8


|station_eu_code |p16_19 |p20  |Valida | region_id|regione |provincia |
|:---------------|:------|:----|:------|---------:|:-------|:---------|
|IT1215A         |TRUE   |TRUE |TRUE   |         5|VENETO  |Rovigo    |
|IT1336A         |TRUE   |TRUE |TRUE   |         5|VENETO  |Verona    |
|IT1838A         |TRUE   |TRUE |TRUE   |         5|VENETO  |Vicenza   |
|IT1848A         |TRUE   |TRUE |TRUE   |         5|VENETO  |Verona    |
|IT1880A         |TRUE   |TRUE |TRUE   |         5|VENETO  |Padova    |
|IT2071A         |TRUE   |TRUE |TRUE   |         5|VENETO  |Padova    |
|IT2072A         |TRUE   |TRUE |TRUE   |         5|VENETO  |Rovigo    |
|IT2231A         |TRUE   |TRUE |TRUE   |         5|VENETO  |Treviso   |


## SARDEGNA : 13


|station_eu_code |p16_19 |p20  |Valida | region_id|regione  |provincia         |
|:---------------|:------|:----|:------|---------:|:--------|:-----------------|
|IT1243A         |TRUE   |TRUE |TRUE   |        20|SARDEGNA |Sassari           |
|IT1269A         |TRUE   |TRUE |TRUE   |        20|SARDEGNA |Cagliari          |
|IT1273A         |TRUE   |TRUE |TRUE   |        20|SARDEGNA |Carbonia-Iglesias |
|IT1309A         |TRUE   |TRUE |TRUE   |        20|SARDEGNA |Olbia-Tempio      |
|IT1397A         |TRUE   |TRUE |TRUE   |        20|SARDEGNA |Cagliari          |
|IT1576A         |TRUE   |TRUE |TRUE   |        20|SARDEGNA |Carbonia-Iglesias |
|IT1993A         |TRUE   |TRUE |TRUE   |        20|SARDEGNA |Cagliari          |
|IT2005A         |TRUE   |TRUE |TRUE   |        20|SARDEGNA |Olbia-Tempio      |
|IT2009A         |TRUE   |TRUE |TRUE   |        20|SARDEGNA |Sassari           |
|IT2010A         |TRUE   |TRUE |TRUE   |        20|SARDEGNA |Sassari           |
|IT2011A         |TRUE   |TRUE |TRUE   |        20|SARDEGNA |Cagliari          |
|IT2056A         |TRUE   |TRUE |TRUE   |        20|SARDEGNA |Cagliari          |
|IT2059A         |TRUE   |TRUE |TRUE   |        20|SARDEGNA |Sassari           |


## PA_BOLZANO : 1


|station_eu_code |p16_19 |p20  |Valida | region_id|regione    |provincia |
|:---------------|:------|:----|:------|---------:|:----------|:---------|
|IT1334A         |TRUE   |TRUE |TRUE   |        41|PA_BOLZANO |Bolzano   |


## CAMPANIA : 2


|station_eu_code |p16_19 |p20  |Valida | region_id|regione  |provincia |
|:---------------|:------|:----|:------|---------:|:--------|:---------|
|IT1487A         |TRUE   |TRUE |TRUE   |        15|CAMPANIA |Caserta   |
|IT2214A         |TRUE   |TRUE |TRUE   |        15|CAMPANIA |Salerno   |


## BASILICATA : 4


|station_eu_code |p16_19 |p20  |Valida | region_id|regione    |provincia |
|:---------------|:------|:----|:------|---------:|:----------|:---------|
|IT1585A         |TRUE   |TRUE |TRUE   |        17|BASILICATA |Potenza   |
|IT1895A         |TRUE   |TRUE |TRUE   |        17|BASILICATA |Matera    |
|IT1897A         |TRUE   |TRUE |TRUE   |        17|BASILICATA |Potenza   |
|IT2205A         |TRUE   |TRUE |TRUE   |        17|BASILICATA |Potenza   |


## PUGLIA : 4


|station_eu_code |p16_19 |p20  |Valida | region_id|regione |provincia |
|:---------------|:------|:----|:------|---------:|:-------|:---------|
|IT1611A         |TRUE   |TRUE |TRUE   |        16|PUGLIA  |Taranto   |
|IT1658A         |TRUE   |TRUE |TRUE   |        16|PUGLIA  |Brindisi  |
|IT1704A         |TRUE   |TRUE |TRUE   |        16|PUGLIA  |Brindisi  |
|IT2139A         |TRUE   |TRUE |TRUE   |        16|PUGLIA  |Brindisi  |


## MOLISE : 1


|station_eu_code |p16_19 |p20  |Valida | region_id|regione |provincia |
|:---------------|:------|:----|:------|---------:|:-------|:---------|
|IT1804A         |TRUE   |TRUE |TRUE   |        14|MOLISE  |Isernia   |


## SICILIA : 3


|station_eu_code |p16_19 |p20  |Valida | region_id|regione |provincia |
|:---------------|:------|:----|:------|---------:|:-------|:---------|
|IT1888A         |TRUE   |TRUE |TRUE   |        19|SICILIA |Palermo   |
|IT1889A         |TRUE   |TRUE |TRUE   |        19|SICILIA |Palermo   |
|IT1890A         |TRUE   |TRUE |TRUE   |        19|SICILIA |Enna      |


## FRIULI_VENEZIA_GIULIA : 2


|station_eu_code |p16_19 |p20  |Valida | region_id|regione               |provincia |
|:---------------|:------|:----|:------|---------:|:---------------------|:---------|
|IT2152A         |TRUE   |TRUE |TRUE   |         6|FRIULI_VENEZIA_GIULIA |Udine     |
|IT2169A         |TRUE   |TRUE |TRUE   |         6|FRIULI_VENEZIA_GIULIA |Udine     |

